# Generated by Django 6.0.2 on 2026-03-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='subscribed_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='active',
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight loss'), ('wellness_longevity', 'Wellness and longevity'), ('energy_vitality', 'Energy and vitality'), ('balance_mobility', 'Balance and mobility')], max_length=50),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='wants_starter_plan',
            field=models.BooleanField(default=False),
        ),
    ]
