# Generated by Django 6.0.2 on 2026-05-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='member_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
